vmd     -dispdev     text     -e     dencity_01.tcl
vmd     -dispdev     text     -e     dencity_02.tcl
vmd     -dispdev     text     -e     dencity_03.tcl
vmd     -dispdev     text     -e     dencity_04.tcl
vmd     -dispdev     text     -e     dencity_05.tcl
vmd     -dispdev     text     -e     dencity_06.tcl
vmd     -dispdev     text     -e     dencity_07.tcl
vmd     -dispdev     text     -e     dencity_08.tcl
vmd     -dispdev     text     -e     dencity_09.tcl
vmd     -dispdev     text     -e     dencity_10.tcl
vmd     -dispdev     text     -e     dencity_11.tcl
vmd     -dispdev     text     -e     dencity_12.tcl
vmd     -dispdev     text     -e     dencity_13.tcl
vmd     -dispdev     text     -e     dencity_14.tcl
vmd     -dispdev     text     -e     dencity_15.tcl
vmd     -dispdev     text     -e     dencity_16.tcl
vmd     -dispdev     text     -e     dencity_17.tcl
vmd     -dispdev     text     -e     dencity_18.tcl
vmd     -dispdev     text     -e     dencity_19.tcl
vmd     -dispdev     text     -e     dencity_20.tcl
vmd     -dispdev     text     -e     dencity_21.tcl
vmd     -dispdev     text     -e     dencity_22.tcl
vmd     -dispdev     text     -e     dencity_23.tcl
vmd     -dispdev     text     -e     dencity_24.tcl
vmd     -dispdev     text     -e     dencity_25.tcl
vmd     -dispdev     text     -e     dencity_26.tcl
vmd     -dispdev     text     -e     dencity_27.tcl
vmd     -dispdev     text     -e     dencity_28.tcl
vmd     -dispdev     text     -e     dencity_29.tcl
vmd     -dispdev     text     -e     dencity_30.tcl
vmd     -dispdev     text     -e     dencity_31.tcl
vmd     -dispdev     text     -e     dencity_32.tcl
vmd     -dispdev     text     -e     dencity_33.tcl
vmd     -dispdev     text     -e     dencity_34.tcl
vmd     -dispdev     text     -e     dencity_35.tcl
vmd     -dispdev     text     -e     dencity_36.tcl
vmd     -dispdev     text     -e     dencity_37.tcl
vmd     -dispdev     text     -e     dencity_38.tcl
vmd     -dispdev     text     -e     dencity_39.tcl
vmd     -dispdev     text     -e     dencity_40.tcl
vmd     -dispdev     text     -e     dencity_41.tcl
vmd     -dispdev     text     -e     dencity_42.tcl
vmd     -dispdev     text     -e     dencity_43.tcl
vmd     -dispdev     text     -e     dencity_44.tcl
vmd     -dispdev     text     -e     dencity_45.tcl
vmd     -dispdev     text     -e     dencity_46.tcl
vmd     -dispdev     text     -e     dencity_47.tcl
vmd     -dispdev     text     -e     dencity_48.tcl
vmd     -dispdev     text     -e     dencity_49.tcl
vmd     -dispdev     text     -e     dencity_50.tcl
vmd     -dispdev     text     -e     dencity_51.tcl
vmd     -dispdev     text     -e     dencity_52.tcl
vmd     -dispdev     text     -e     dencity_53.tcl
vmd     -dispdev     text     -e     dencity_54.tcl
vmd     -dispdev     text     -e     dencity_55.tcl
vmd     -dispdev     text     -e     dencity_56.tcl
vmd     -dispdev     text     -e     dencity_57.tcl
vmd     -dispdev     text     -e     dencity_58.tcl
vmd     -dispdev     text     -e     dencity_59.tcl
vmd     -dispdev     text     -e     dencity_60.tcl
